/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Contact;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-02-08T12:06:08.865Z")

@Api(value = "api", description = "the api API")
@RequestMapping(value = "")
public interface ApiApi {

    @ApiOperation(value = "addContact", nickname = "addContactUsingPOST", notes = "", response = Contact.class, tags={ "address-book-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Contact.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/addContact",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Contact> addContactUsingPOST(@ApiParam(value = "contact" ,required=true )  @Valid @RequestBody Contact contact);


    @ApiOperation(value = "getAllContacts", nickname = "getAllContactsUsingGET", notes = "", response = Contact.class, responseContainer = "List", tags={ "address-book-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Contact.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/getAllContacts",
        produces = { "*/*" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Contact>> getAllContactsUsingGET();

}
